# Generated by Django 4.1.13 on 2024-01-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebHook',
        ),
    ]
